SELECT * FROM T_STUDENT;
-- dual 은 ROW 1개 짜리 더미 테이블;
SELECT 'abced' FROM dual;
SELECT '안녕하세요' FROM dual;
SELECT 100 FROM dual;
SELECT 100+10 FROM dual;
SELECT * FROM t_emp;
SELECT EMPNO,ENAME FROM t_emp;
SELECT name FROM T_PROFESSOR ;
SELECT STUDNO AS "학생 학번" ,name AS 이름 FROM T_STUDENT ;

SELECT ENAME 사원명,job 직업 FROM T_EMP; 
SELECT DEPTNO "부서#" ,DNAME "부서명",loc "위치" FROM T_DEPT;

SELECT * FROM t_emp;
SELECT DISTINCT DEPTNO FROM t_emp;

SELECT DISTINCT DEPTNO1 FROM T_STUDENT ;
SELECT DISTINCT JOB FROM T_EMP ;

SELECT NAME,POSITION FROM T_PROFESSOR ;
SELECT name || '-' || POSITION AS "교수님명단" FROM T_PROFESSOR;

SELECT * FROM T_STUDENT;
SELECT name ||'의 키는'|| HEIGHT || '-' || WEIGHT ||'kg 입니다' AS "신상정보" FROM T_STUDENT;





SELECT t1.ENAME,t2.ENAME FROM T_EMP t1, T_EMP t2 WHERE t1.mgr=7698 AND t1.MGR=t2.EMPNO 