--DB03
--p25~p27
SELECT NAME FROM T_STUDENT WHERE HEIGHT >= 180;
SELECT NAME,WEIGHT FROM T_STUDENT WHERE WEIGHT BETWEEN 60 AND 80;
SELECT NAME,deptno1 FROM T_STUDENT WHERE DEPTNO1 in(101,201);
SELECT NAME FROM T_STUDENT WHERE name LIKE '김%';
SELECT name,GRADE ,HEIGHT FROM T_STUDENT WHERE GRADE=4 AND HEIGHT >=170;
SELECT name,HEIGHT ,WEIGHT FROM T_STUDENT WHERE GRADE=1 AND WEIGHT >=80;
SELECT name,HEIGHT ,WEIGHT FROM T_STUDENT WHERE GRADE=2 AND HEIGHT >180 AND WEIGHT >70;
SELECT name,HEIGHT ,WEIGHT FROM T_STUDENT WHERE GRADE=2 AND HEIGHT >180 OR WEIGHT >70;
SELECT ename,HIREDATE FROM t_emp;
SELECT ename,hiredate FROM t_emp WHERE '1992-01-01' > TO_CHAR(HIREDATE ,'yyyymmdd') ; 
SELECT name,BIRTHDAY ,HEIGHT,WEIGHT FROM T_STUDENT ORDER BY BIRTHDAY;
SELECT NAME AS "이름",HEIGHT AS "키" FROM T_STUDENT WHERE GRADE =1 ORDER BY name asc;
SELECT NAME,BIRTHDAY FROM T_EMP2 WHERE to_char(BIRTHDAY,'yyyymmdd') BETWEEN TO_DATE('19800101') AND TO_DATE('19891231');

SELECT NAME AS "이름",PAY AS "급여" FROM T_PROFESSOR WHERE PAY >= 5000;

--  교수님 이름 | 소속 학과명 |   ← 이렇게 출력될수 있도록 SQL 문을 작성하세

SELECT a.NAME AS "|교수님이름|",b.DNAME AS "|소속학과명|"
FROM T_PROFESSOR a,T_DEPARTMENT b
WHERE a.DEPTNO=b.DEPTNO;

    
--이윤나 학생의 학과와 동일한 학과의 학생들의 
--학생이름 | 학과명 |   이 출력될수 있도록 SQL 문을 작성하세요.

SELECT a.NAME AS "|학생이름|",b.DNAME AS "|학과명|"
FROM T_STUDENT a,T_DEPARTMENT b
WHERE (SELECT DEPTNO1 FROM T_STUDENT WHERE NAME='이윤나')=b.DEPTNO ;
