--산술 연산자--

SELECT ename,sal,sal*1.1 FROM t_emp;

SELECT ENAME ,SAL ,COMM FROM t_emp;
SELECT ENAME ,SAL ,COMM , FROM t_emp;

SELECT * FROM T_EMP WHERE job='SALESMAN';

SELECT * FROM t_emp;
SELECT ENAME ,SAL ,DEPTNO FROM t_emp WHERE DEPTNO =10;
SELECT ENAME ,SAL ,DEPTNO FROM t_emp WHERE sal >2000;
SELECT ENAME ,SAL ,DEPTNO FROM t_emp WHERE ENAME ='SCOTT';

SELECT ename, job FROM t_emp 
     WHERE job IN ('CLERK', 'ANALYST');
    
SELECT GRADE ,NAME FROM T_STUDENT WHERE GRADE IN(2,3);
SELECT GRADE ,NAME FROM T_STUDENT WHERE GRADE NOT IN(1,4);

SELECT NAME ,PAY , POSITION FROM T_PROFESSOR WHERE pay>300 AND POSITION='정교수';
SELECT * FROM T_PROFESSOR;

SELECT name ,POSITION FROM T_PROFESSOR WHERE BONUS IS NULL;
SELECT name FROM T_PROFESSOR WHERE NAME LIKE '김%';
SELECT ENAME FROM T_EMP WHERE ENAME LIKE '%NE%';
SELECT ENAME FROM T_EMP WHERE ENAME LIKE '%L%';

SELECT job,ENAME ,SAL FROM T_EMp ORDER BY job DESC, sal asc;

SELECT name, grade, height FROM t_student ORDER BY grade ASC, height DESC;





